# Generated by Django 2.0.6 on 2018-06-28 02:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companhia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Companhias aéreas',
                'verbose_name': 'Companhia aérea',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Compromisso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_inicio', models.DateTimeField(verbose_name='Data e Hora de início')),
                ('data_hora_fim', models.DateTimeField(verbose_name='Data e Hora de término')),
                ('local', models.CharField(help_text='Local do evento', max_length=60)),
                ('descricao', ckeditor.fields.RichTextField(help_text='Descrição geral do evento, para que o parlamentar saiba do que se trata.', verbose_name='Descrição')),
                ('obs', models.TextField(blank=True, null=True, verbose_name='Observações')),
            ],
            options={
                'ordering': ('data_hora_inicio',),
            },
        ),
        migrations.CreateModel(
            name='TipoCompromisso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Tipos de compromisso',
                'verbose_name': 'Tipo de compromisso',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Voo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_partida', models.DateTimeField(verbose_name='Data e horário de partida')),
                ('data_hora_chegada', models.DateTimeField(verbose_name='Data e horário de chegada')),
                ('localizador', models.CharField(help_text='Código localizador do vôo.', max_length=60)),
                ('numero', models.CharField(help_text='Número do vôo', max_length=20)),
                ('portao', models.CharField(max_length=30, verbose_name='Portão de embarque')),
                ('assento', models.CharField(help_text='Número do assento', max_length=20)),
                ('obs', models.TextField(blank=True, null=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name_plural': 'Vôos',
                'verbose_name': 'Vôo',
                'ordering': ('data_hora_partida',),
            },
        ),
    ]
