# Generated by Django 2.0.5 on 2018-05-23 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gabinete', '0001_initial'),
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companhia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Companhias aéreas',
                'verbose_name': 'Companhia aérea',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Compromisso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora_inicio', models.TimeField(unique_for_date='data', verbose_name='Horário de início')),
                ('hora_fim', models.TimeField(unique_for_date='data', verbose_name='Horário de término')),
                ('local', models.CharField(help_text='Local do evento', max_length=60)),
                ('descricao', models.TextField(help_text='Descrição geral do evento, para que o parlamentar saiba do que se trata.', verbose_name='Descrição')),
                ('obs', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('deputado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gabinete.Deputado')),
            ],
            options={
                'ordering': ('data', 'hora_inicio'),
            },
        ),
        migrations.CreateModel(
            name='TipoCompromisso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('ativo', models.BooleanField(default=True)),
                ('deputado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gabinete.Deputado')),
            ],
            options={
                'verbose_name_plural': 'Tipos de compromissos',
                'verbose_name': 'Tipo de compromisso',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Voo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_partida', models.DateTimeField(verbose_name='Data e horário de partida')),
                ('data_hora_chegada', models.DateTimeField(verbose_name='Data e horário de chegada')),
                ('localizador', models.CharField(help_text='Código localizador do vôo.', max_length=60)),
                ('numero', models.PositiveIntegerField(verbose_name='Número do vôo')),
                ('portao', models.CharField(max_length=30, verbose_name='Portão de embarque')),
                ('assento', models.PositiveIntegerField(verbose_name='Número do assento')),
                ('obs', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('cidade_chegada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cidade_chegada_voo', to='gabinete.Cidade', verbose_name='Cidade de chegada')),
                ('cidade_partida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cidade_partida_voo', to='gabinete.Cidade', verbose_name='Cidade de partida')),
                ('companhia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agenda.Companhia', verbose_name='Companhia aérea')),
                ('deputado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gabinete.Deputado')),
            ],
            options={
                'verbose_name_plural': 'Vôos',
                'verbose_name': 'Vôo',
                'ordering': ('data_hora_partida',),
            },
        ),
        migrations.DeleteModel(
            name='Teste',
        ),
        migrations.AddField(
            model_name='compromisso',
            name='tipo',
            field=models.ForeignKey(help_text='Define o tipo de compromisso do parlamentar. Ex.: Reunião, Evento festivo, Etc.', on_delete=django.db.models.deletion.PROTECT, to='agenda.TipoCompromisso'),
        ),
    ]
