# Generated by Django 2.0.5 on 2018-06-06 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voo',
            name='assento',
            field=models.CharField(help_text='Número do assento', max_length=20),
        ),
        migrations.AlterField(
            model_name='voo',
            name='numero',
            field=models.CharField(help_text='Número do vôo', max_length=20),
        ),
    ]
