# Generated by Django 2.0.6 on 2018-06-10 01:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
            ],
            options={
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Deputado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, verbose_name='Gênero')),
                ('tratamento', models.CharField(blank=True, help_text='Ex.: Dr., Sr., etc.', max_length=60, null=True, verbose_name='Pronome de tratamento')),
                ('nome', models.CharField(max_length=60)),
                ('mensagem', models.CharField(blank=True, help_text='Exibida em documentos, junto à assinatura do parlamentar.', max_length=60, null=True, verbose_name='Mensagem de assinatura')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('nome',),
                'verbose_name_plural': 'Parlamentares',
                'verbose_name': 'Parlamentar',
            },
        ),
        migrations.CreateModel(
            name='EnderecoDeputado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(help_text='Nome da rua ou avenida.', max_length=100)),
                ('numero', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número')),
                ('bairro', models.CharField(max_length=60)),
                ('complemento', models.CharField(blank=True, max_length=60, null=True)),
                ('telefone', models.CharField(max_length=30)),
                ('fax', models.CharField(blank=True, max_length=30, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gabinete.Cidade')),
                ('deputado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gabinete.Deputado')),
            ],
            options={
                'ordering': ('id',),
                'verbose_name_plural': 'Endereços do parlamentar',
                'verbose_name': 'Endereço do parlamentar',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('sigla', models.CharField(max_length=2)),
            ],
            options={
                'ordering': ('sigla',),
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
            ],
            options={
                'ordering': ('nome',),
                'verbose_name_plural': 'Países',
                'verbose_name': 'País',
            },
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('sigla', models.CharField(max_length=30)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('sigla',),
            },
        ),
        migrations.CreateModel(
            name='Regional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('ativo', models.BooleanField(default=True)),
                ('deputado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gabinete.Deputado')),
            ],
            options={
                'ordering': ('nome',),
                'verbose_name_plural': 'Regionais',
                'verbose_name': 'Regional',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deputado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gabinete.Deputado')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Usuários',
                'verbose_name': 'Usuário',
            },
        ),
        migrations.AddField(
            model_name='estado',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gabinete.Pais'),
        ),
        migrations.AddField(
            model_name='deputado',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gabinete.Estado', verbose_name='Estado de atuação'),
        ),
        migrations.AddField(
            model_name='deputado',
            name='partido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gabinete.Partido'),
        ),
        migrations.AddField(
            model_name='cidade',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gabinete.Estado'),
        ),
    ]
