# Generated by Django 2.0.5 on 2018-07-15 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gabinete', '0002_auto_20180715_1055'),
        ('oficios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailPessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('obs', models.TextField(blank=True, null=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'E-mail de Pessoa',
                'verbose_name_plural': 'E-mail de Pessoas',
            },
        ),
        migrations.CreateModel(
            name='EnderecoPessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=8)),
                ('logradouro', models.CharField(help_text='Nome da rua ou avenida.', max_length=100)),
                ('numero', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número')),
                ('bairro', models.CharField(max_length=60)),
                ('complemento', models.CharField(blank=True, max_length=60, null=True)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gabinete.Cidade')),
            ],
            options={
                'verbose_name': 'Emdereço de Pessoa',
                'verbose_name_plural': 'Endereço de Pessoas',
                'ordering': ('cidade',),
            },
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gabinete.Cidade')),
                ('deputado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gabinete.Deputado')),
                ('regional', models.ForeignKey(help_text='Regional a qual pertence a instituição.', on_delete=django.db.models.deletion.PROTECT, to='gabinete.Regional')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pronome', models.CharField(choices=[('À', 'À'), ('Ao', 'Ao')], help_text='Utilizado na emissão de documentos.', max_length=2)),
                ('tratamento', models.CharField(blank=True, help_text='Pronome de tratamento incluído nos documentos emitidos. Ex.: Vossa Excelência o Sr.', max_length=60, null=True)),
                ('nome', models.CharField(max_length=60)),
                ('inicio_mandato', models.DateField(blank=True, null=True, verbose_name='Início do mandato')),
                ('fim_mandato', models.DateField(blank=True, null=True, verbose_name='Fim do mandato')),
                ('ativo', models.BooleanField(default=True)),
                ('cargo', models.ForeignKey(blank=True, help_text='Cargo que a pessoa trabalha.', null=True, on_delete=django.db.models.deletion.PROTECT, to='oficios.Cargo')),
                ('deputado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gabinete.Deputado')),
                ('instituicao', models.ForeignKey(blank=True, help_text='Instituição em qual a pessoa trabalha.', null=True, on_delete=django.db.models.deletion.PROTECT, to='oficios.Instituicao')),
                ('partido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gabinete.Partido')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='TelefonePessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(blank=True, max_length=30, null=True)),
                ('obs', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oficios.Pessoa')),
            ],
            options={
                'verbose_name': 'Contato de Pessoa',
                'verbose_name_plural': 'Contatos de Pessoas',
            },
        ),
        migrations.RemoveField(
            model_name='contatoentidade',
            name='entidade',
        ),
        migrations.RemoveField(
            model_name='entidade',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='entidade',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='entidade',
            name='deputado',
        ),
        migrations.RemoveField(
            model_name='entidade',
            name='partido',
        ),
        migrations.RemoveField(
            model_name='entidade',
            name='regional',
        ),
        migrations.DeleteModel(
            name='ContatoEntidade',
        ),
        migrations.DeleteModel(
            name='Entidade',
        ),
        migrations.AddField(
            model_name='enderecopessoa',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oficios.Pessoa'),
        ),
        migrations.AddField(
            model_name='emailpessoa',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oficios.Pessoa'),
        ),
    ]
